json.array! @restaurants,
              :id,
              :name,
              :description,
              :location,
              :hours,
              :rating,
              :price_range,
              :phone_number,
              :neighborhood,
              :photos,
              :get_lng_lat
