json.extract! @restaurant,
              :id,
              :name,
              :description,
              :location,
              :hours,
              :rating,
              :price_range,
              :phone_number,
              :neighborhood,
              :photos,
              :reviews,
              :users
