json.extract!(@review,
              :id,
              :user_id,
              :restaurant_id,
              :body,
              :rating,
              :cool,
              :funny,
              :useful)
